import { gql } from "@apollo/client";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { AiFillStar } from "react-icons/ai";
import { VscRepoForked } from "react-icons/vsc";
import useSWR from "swr";
import { getApolloClient } from "../apollo-client";
import { CardLink } from "../components/CardLink";
import LinePlot from "../components/LinePlot/LinePlot";
import { Repo } from "../models";
import styles from "../styles/Home.module.css";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const repositories = [
  { owner: "ethereum", repo: "go-ethereum" },
  { owner: "paritytech", repo: "polkadot" },
  { owner: "ava-labs", repo: "avalanchego" },
  { owner: "cosmos", repo: "ibc-go" },
  { owner: "solana-labs", repo: "solana" },
];

const BarPlot = ({ name }: string) => {
  const [owner, repo] = name.split("/");

  const { data, error } = useSWR(
    `/api/github?owner=${owner}&repo=${repo}`,
    fetcher
  );

  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;

  return (
    <div className={styles.plot}>
      <LinePlot
        data={data.data.data}
        width={300}
        height={100}
        className={styles.plot_object}
      />
    </div>
  );
};

const Home: NextPage = ({ repo }: Repo) => {
  const openList = repositories.map(() => false);
  const [open, setOpen] = useState(openList);

  const handlePlotClick = (i: number) => {
    const list = [...open];
    list[i] = !list[i];

    console.log("list", list);
    setOpen(list);
  };

  const repoCard = Object.keys(repo).map((key: string, index) => {
    return (
      <div className={styles.repocard} key={key}>
        <CardLink href={`/${repo[key].nameWithOwner}`}>
          <h2>{repo[key].nameWithOwner}</h2>
          <h3>{repo[key].description}</h3>
          <h3>{repo[key].name}</h3>
          <p>
            <AiFillStar />: {repo[key].stargazerCount}
          </p>
          <p>
            <VscRepoForked />: {repo[key].forkCount}
          </p>
          <button onClick={() => handlePlotClick(index)}>show plot</button>
          {open[index] && <BarPlot name={repo[key].nameWithOwner} />}
        </CardLink>
      </div>
    );
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>GitHub projects by development effort</h1>
        <p>
          Disclaimer: The merit of a project cannot be judged solely on the
          metrics shown here. Use your judgement.
        </p>
        <div className={styles.grid}>{repoCard}</div>
      </main>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const client = getApolloClient();

  const { data } = await client.query<Repo>({
    query: gql`
      fragment repoProperties on Repository {
        id
        description
        forkCount
        name
        nameWithOwner
        stargazerCount
        issues {
          totalCount
        }
        mentionableUsers {
          totalCount
        }
        assignableUsers {
          totalCount
        }
        pullRequests {
          totalCount
        }
        object(expression: "master") {
          ... on Commit {
            id
            history {
              totalCount
            }
          }
        }
      }
      
      {
        ${repositories
          .map(
            ({ owner, repo }, index) => `repo${
              index + 1
            }: repository(owner: "${owner}", name: "${repo}") {
          ...repoProperties
        }`
          )
          .join("\n")}
      }`,
  });

  const repo = data;

  return {
    props: {
      repo,
    },
  };
}
